#+Lgr


#+begin_export latex
\begin{align*}
D_{SKL}(\mathbb{P} \, , \, \mathbb{Q}) = \sum_{x \in \mathcal{X}} \mathbb{P}(X=x)\log \frac{\mathbb{P}(X = x)}{\mathbb{Q}(X=x)} + \mathbb{Q}(X=x)\log \frac{\mathbb{Q}(X = x)}{\mathbb{P}(X=x)}
\end{align*}
#+end_export


We apply Algorithm \ref{alg:cstreepc} to the setup above, and record the CStrees with the minimum number of stages over all possible causal orderings, alongside their BIC scores. If we have CStrees with the same number of minimum stages, we record the highest BIC score among them. We call this *experimental setup 1*, and the result are summarized in the Table \ref{table:coronary1}.


    Here we see that the minimum number of stages over all the configurations is 6, and the result CStree is shown in Figure \ref{fig:coronary1}. The causal ordering is 346125, and we get this CStree by learning the original DAG using the PC algorithm, followed by the Anderson-Darling test to learn context specific information without encoding the CI relations from the original DAG. However it can be seen that the BIC score is lower compared to the CStree generated from the DAG itself and the CStree learnt using the CI relations in the DAG before learning the context specific information. The latter CStree also has more stages than the CStree learnt without using the CI relations, which can be explained by the possibility that the DAG encoded CI relation(s) which put nodes in the same stage, which otherwise may have been put in the same stage from the context specific testing procedure. Among the trees with the lowest stages, the CStree with the highest BIC score is generated with the ordering 534126, using the symmetric KL divergence with a threshold of $5e^{-5}$ for the staging procedure, from the DAG learnt from the Hill Climbing algorithm and without encoding the CI relations from it. It shown in Figure \ref{fig:coronary2} We see that this CStree has 27 stages, which motivates us to define the *experimental setup 2*, where we aim to find the CStree with the highest BIC score instead of the minimum number of stages as in the experimental setup 1. We show the results of this in Table \ref{table:coronary2}.


We see that the results are nearly identical, other than for 2 entries corresponding to the Epps-Singleton test and symmetric KL divergence with threshold $5^{-5}$ which have an improved BIC score for the CStree learnt without the CI relations from the DAG. This could be due to the dataset allowing for few consistent causal orderings.


#+begin_export latex

% Please add the following required packages to your document preamble:
% \usepackage{multirow}
\begin{table*}[]\label{table:coronary1}
\begin{tabular}{cccccccccccccccc}
\cline{3-12}
                        & \multicolumn{1}{c|}{\multirow{\begin{tabular}[c]{@{}c@{}}Goal:\\ Min stages\end{tabular}}} & \multicolumn{2}{c|}{Anderson}                                  & \multicolumn{2}{c|}{Epps}                                  & \multicolumn{2}{c|}{SKL $5 \times 10^{-5}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-6}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-7}$}                                     &  &  &  &  \\ \cline{3-12}
                        & \multicolumn{1}{c|}{}                                                                            & \multicolumn{1}{c|}{Stages}     & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              &  &  &  &  \\ \cline{3-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{18}         & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{PC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{\textbf{6}} & \multicolumn{1}{c|}{-6783.7} & \multicolumn{1}{c|}{13}     & \multicolumn{1}{c|}{-6812.1} & \multicolumn{1}{c|}{23}     & \multicolumn{1}{c|}{-6757.1} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-7032.3} & \multicolumn{1}{c|}{44}     & \multicolumn{1}{c|}{-6753.4}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{8}          & \multicolumn{1}{c|}{-6771.3} & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-6780.4} & \multicolumn{1}{c|}{15}     & \multicolumn{1}{c|}{-6775.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4}          &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{31}         & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{HC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{8}          & \multicolumn{1}{c|}{-6786.5} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6837.3} & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-6799.0} & \multicolumn{1}{c|}{39}     & \multicolumn{1}{c|}{-6828.0} & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-6755.9}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{8}          & \multicolumn{1}{c|}{-6788.7} & \multicolumn{1}{c|}{15}     & \multicolumn{1}{c|}{-6809.7} & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-6801.4} & \multicolumn{1}{c|}{23}     & \multicolumn{1}{c|}{-6805.4} & \multicolumn{1}{c|}{30}     & \multicolumn{1}{c|}{\textbf{-6729.5}} &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  & 

\caption{Experimental setup 1 on the coronary dataset. Each cell under the column "Stages" is the minimum number of stages amongst all causal orderings generated from the either the PC or Hill Climbing algorithm, for different staging criteria. Many orderings produce CStrees with the same number of stages, the BIC score in the table above is the maximum such BIC score.}
\end{tabular}
\end{table*}

#+end_export

#+begin_export latex
\begin{figure}[]\label{fig:coronary1}
   \begin{floatrow}
\ffigbox{\includegraphics[width=1.1\linewidth]{temp/coronaryminstages1.pdf}}%
\caption{CStree for the coronary dataset with the lowest number of stages, which has ordering 346125.}
        
   \end{floatrow}
\end{figure}

\begin{figure}[]\label{fig:coronary2}
   \begin{floatrow}
\ffigbox{\includegraphics[width=1.1\linewidth]{temp/coronaryminstages1topbic.pdf}}%
\caption{CStree with the highest BIC score among all CStrees with the minimum number of stages in experimental setup 1, which has ordering 534126.}
        
   \end{floatrow}
\end{figure}
#+end_export



#+begin_export latex
% Please add the following required packages to your document preamble:
% \usepackage{multirow}
\begin{table*}[]\label{table:coronary2}
\begin{tabular}{cccccccccccccccc}
\cline{3-12}
                        & \multicolumn{1}{c|}{\multirow{\begin{tabular}[c]{@{}c@{}}Goal:\\ Min stages\end{tabular}}} & \multicolumn{2}{c|}{Anderson}                                  & \multicolumn{2}{c|}{Epps}                                  & \multicolumn{2}{c|}{SKL $5 \times 10^{-5}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-6}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-7}$}                                     &  &  &  &  \\ \cline{3-12}
                        & \multicolumn{1}{c|}{}                                                                            & \multicolumn{1}{c|}{Stages}     & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              &  &  &  &  \\ \cline{3-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{18}         & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{PC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{\textbf{7}} & \multicolumn{1}{c|}{-6783.7} & \multicolumn{1}{c|}{13}     & \multicolumn{1}{c|}{-6812.1} & \multicolumn{1}{c|}{23}     & \multicolumn{1}{c|}{-6757.1} & \multicolumn{1}{c|}{43}     & \multicolumn{1}{c|}{-6749.6} & \multicolumn{1}{c|}{44}     & \multicolumn{1}{c|}{-6753.4}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{8}          & \multicolumn{1}{c|}{-6771.3} & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-6780.4} & \multicolumn{1}{c|}{15}     & \multicolumn{1}{c|}{-6775.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4} & \multicolumn{1}{c|}{18}     & \multicolumn{1}{c|}{-6739.4}          &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{31}         & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6733.3}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{HC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{8}          & \multicolumn{1}{c|}{-6786.5} & \multicolumn{1}{c|}{31}     & \multicolumn{1}{c|}{-6837.3} & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-6799.0} & \multicolumn{1}{c|}{39}     & \multicolumn{1}{c|}{-6828.0} & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-6755.9}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{8}          & \multicolumn{1}{c|}{-6788.7} & \multicolumn{1}{c|}{15}     & \multicolumn{1}{c|}{-6809.7} & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-6801.4} & \multicolumn{1}{c|}{23}     & \multicolumn{1}{c|}{-6805.4} & \multicolumn{1}{c|}{30}     & \multicolumn{1}{c|}{\textbf{-6729.5}} &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                                       &  &  &  & 

\caption{Experimental setup 2 on the coronary dataset, the only difference to experimental setup 1 is that we now maximize the BIC score over all possible causal orderings.}
			\end{tabular}
\end{table*}
#+end_export

    In order to generate the sequence of DAGs that capture the context specific causal information from this dataset, we require 4 variables for computational feasibility. We do this by first removing the variable that gives us the the best score after its removal, which in this case is the variable corresponding to systolic blood pressure. We then generate the 5 BIC optimal CSTrees arising after removing each of the remaining 5 variables.

 # TODO In order to see the true discrepancy between the BIC score of DAGs and CStrees, we consider another method to get a starting DAG. This is to do an exhaustive search over the space of DAGs, and choose the DAG with the highest BIC score, and take the DAGs in its MEC to generate the possible causal orderings. We call this *experimental setup 3*. This task is intractable for variables more than 5, thus we have to remove 1 variable. To decide on which variable to choose, we generate all possible DAGs after removing each variable separately, and remove the variable which results in the highest BIC score. For this dataset, this happens to be the systolic blood pressure.

# Applying Algorithm \ref{alg:cstreepc} yields 55 CStrees which have the same number of stages, which is 69. If we exclude singleton stages corresponding to the last level this is 5 stages, which results in a full independence model.

# This motivated the exploration of other CStrees with a causal ordering consistent with the CPDAG. In total the coronary dataset gave rise to 288 trees, and although much of it resulted in very sparse CStrees, i.e. those with very few stages close to the minimum stages, there were some models which were more complex than this, one of which we show below. The amount of context specific independence tests skipped due to no available data was at most around 25 per CStree.





# TODO cite table number for above

# TODO With or withot DAG encodings

# TODO Print all possible orderings
{{{NEWPAGE}}}

** Mice protein expression data
   This is a dataset with expression levels of 77 proteins, measured in the cerebral cortex of 8 classes of mice cite:higuera-2015-self-organ. There are 38 control mice and 34 trisomic mice, and for each of them 15 separate measurements were taken which gives a total of 1080 samples. The aim is to identify features that can discriminate between the 8 classes that make up all possible combinations of the following 3 binary features - Control or Trisonomy, stimulated to learn or not, injected with saline or memantine. This dataset had missing values, which is why we handle by first inspecting the missing value counts for each feature and then removing features which had 180 or more missing values. This removes the expression data corresponding to the columns $BAD_N, BCL2_N, H3AcK18_N, EGR1_N, H3MeK4_N$. This still leaves 72 features, which we further reduce by recursive feature elimination cite:guyon-2002 where we first train a linear support vector classifier on all the features and prune the least important features in a greedy manner until we arrive at the number of features we want. After this we compute the medians for each feature and assign each feature to take binary outcomes depending on whether or not the value is above or below the median.



   We choose 7 features and the predictor variable, giving a system of 8 variables. This number is chosen since this gives a maximum of 196 causal orderings which is computationally feasible, meanwhile increasing the variables to 9 and 10 increase this amount to 1008 and 13608 respectively. 


   #+begin_export latex
% Please add the following required packages to your document preamble:
% \usepackage{multirow}
\begin{table*}[]\label{table:mice1}
\begin{tabular}{cccccccccccccccc}
\cline{3-12}
                        & \multicolumn{1}{c|}{\multirow{\begin{tabular}[c]{@{}c@{}}Goal:\\ Min Stages\end{tabular}}} & \multicolumn{2}{c|}{Anderson}                                  & \multicolumn{2}{c|}{Epps}                                  & \multicolumn{2}{c|}{SKL $5 \times 10^{-4}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-5}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-6}$}                            &  &  &  &  \\ \cline{3-12}
                        & \multicolumn{1}{c|}{}                                                                            & \multicolumn{1}{c|}{Stages}     & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     &  &  &  &  \\ \cline{3-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{154}        & \multicolumn{1}{c|}{-5615.9} & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9} & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9} & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9} & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{PC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CStree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{\textbf{7}} & \multicolumn{1}{c|}{-6555.4} & \multicolumn{1}{c|}{8}      & \multicolumn{1}{c|}{-6442.3} & \multicolumn{1}{c|}{61}     & \multicolumn{1}{c|}{-5678.9} & \multicolumn{1}{c|}{64}     & \multicolumn{1}{c|}{-5640.6} & \multicolumn{1}{c|}{78}     & \multicolumn{1}{c|}{-5587.6} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CStree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{11}         & \multicolumn{1}{c|}{-6591.4} & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-6591.4} & \multicolumn{1}{c|}{15}     & \multicolumn{1}{c|}{-5702.0} & \multicolumn{1}{c|}{68}     & \multicolumn{1}{c|}{-5705.4} & \multicolumn{1}{c|}{71}     & \multicolumn{1}{c|}{-5692.2} &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{102}        & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{HC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CStree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{13}         & \multicolumn{1}{c|}{-6373.8} & \multicolumn{1}{c|}{82}     & \multicolumn{1}{c|}{-6095.1} & \multicolumn{1}{c|}{33}     & \multicolumn{1}{c|}{-6017.8} & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5857.2} & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5857.2} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CStree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{12}         & \multicolumn{1}{c|}{-6404.1} & \multicolumn{1}{c|}{20}     & \multicolumn{1}{c|}{-6179.9} & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5852.3} & \multicolumn{1}{c|}{49}     & \multicolumn{1}{c|}{-5815.0} & \multicolumn{1}{c|}{59}     & \multicolumn{1}{c|}{-5837.1} &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  &  \\
                        &                                                                                                  &                                 &                              &                             &                              &                             &                              &                             &                              &                             &                              &  &  &  & 
\caption{Experimental setup 1 on the mice protein expression dataset}
			\end{tabular}
\end{table*}
   #+end_export


   The results from Table \ref{table:mice1} show once again that the Anderson-Darling test tends to merge stages more often thus resulting in a CStree with the minimum number of stages at the expense of a worse fit to the data, as indicated by the BIC score. We show the result of experimental setup 2 on this dataset in Table \ref{table:mice2}



   #+begin_export latex
% Please add the following required packages to your document preamble:
% \usepackage{multirow}


\begin{table*}[]\label{table:mice2}
\begin{tabular}{cccccccccccccccc}
\cline{3-12}
                        & \multicolumn{1}{c|}{\multirow{\begin{tabular}[c]{@{}c@{}}Goal:\\ Max BIC\end{tabular}}} & \multicolumn{2}{c|}{Anderson}                                  & \multicolumn{2}{c|}{Epps}                                  & \multicolumn{2}{c|}{SKL $5 \times 10^{-4}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-5}$}                            & \multicolumn{2}{c|}{SKL $5 \times 10^{-6}$}                            &  &  &  &  \\ \cline{3-12}


                        & \multicolumn{1}{c|}{}                                                                         & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              &  &  &  &  \\ \cline{3-12}
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                      & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9}          & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9}          & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9}          & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9}          & \multicolumn{1}{c|}{154}    & \multicolumn{1}{c|}{-5615.9}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{PC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                  & \multicolumn{1}{c|}{15}     & \multicolumn{1}{c|}{-6542.4}          & \multicolumn{1}{c|}{45}     & \multicolumn{1}{c|}{-5804.4}          & \multicolumn{1}{c|}{113}    & \multicolumn{1}{c|}{-5474.4}          & \multicolumn{1}{c|}{115}    & \multicolumn{1}{c|}{-5513.2}          & \multicolumn{1}{c|}{133}    & \multicolumn{1}{c|}{\textbf{-5433.0}} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-6591.4}          & \multicolumn{1}{c|}{36}     & \multicolumn{1}{c|}{-5906.2}          & \multicolumn{1}{c|}{75}     & \multicolumn{1}{c|}{-5598.9}          & \multicolumn{1}{c|}{76}     & \multicolumn{1}{c|}{-5602.4}          & \multicolumn{1}{c|}{79}     & \multicolumn{1}{c|}{-5589.1}          &  &  &  &  \\ \cline{2-12}
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                      & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} & \multicolumn{1}{c|}{102}    & \multicolumn{1}{c|}{\textbf{-5376.6}} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{HC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                  & \multicolumn{1}{c|}{13}     & \multicolumn{1}{c|}{-6373.8}          & \multicolumn{1}{c|}{85}     & \multicolumn{1}{c|}{-6019.9}          & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5857.2}          & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5857.2}          & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5857.2}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                & \multicolumn{1}{c|}{13}     & \multicolumn{1}{c|}{-6387.2}          & \multicolumn{1}{c|}{21}     & \multicolumn{1}{c|}{-6149.2}          & \multicolumn{1}{c|}{41}     & \multicolumn{1}{c|}{-5852.3}          & \multicolumn{1}{c|}{49}     & \multicolumn{1}{c|}{-5815.0}          & \multicolumn{1}{c|}{59}     & \multicolumn{1}{c|}{-5837.1}          &  &  &  &  \\ \cline{2-12}
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                               &                             &                                       &                             &                                       &                             &                                       &                             &                                       &                             &                                       &  &  &  & 
\caption{Experimental setup 2 on the mice protein expression dataset.}
			\end{tabular}
\end{table*}
   #+end_export



   # TODO mention many skipped tests for this dataset

   # TODO detail tableThe 6 features we use are detailed below.

   # !!! TODO create variable table for above

   # TODO With or without DAG independence encoding

   # TODO Print all possible orderings

   # TODO mention that encoding CI relations before hand helps with data sparsity
   # TODO run coronary dataset again to consider ALL orderings

 {{{NEWPAGE}}}

** Supersymmetry data

   This is a simulated dataset involving 8 kinematic features measured by detectors in a particle accelerator alongside 10 more high-level features which are functions of the original 8 features cite:baldi-2014-searc-exotic. The aim is is to identify the class label for each sample which denotes whether the measurement corresponds to a signal or background event. The dataset contains in total 5000000 samples. There are no missing values in this dataset, and we apply it on the 8 low-level features, and after taking a random subsample of size 2500000 samples. Our aim with using this dataset is to assess the empirical feasibility of our methods on large sample sizes. The number of valid causal orderings varies largely depending on the subsampled data, which ranged from 200 to 8000 in our experiments. As a result, we simply learn the CStree with the first ordering in the algorithm. 

        #+begin_export latex
\begin{figure}[H]\label{fig:susy1}
   \begin{floatrow}
\ffigbox{\includegraphics[width=1.1\linewidth]{temp/susy1_cstree.pdf}}%
\caption{First CStree learnt from the supersymmetry dataset.}
        
   \end{floatrow}
\end{figure}
   #+end_export

   It is expected that since the supersymmetry data involves many causal interactions, there will be few independence relations, which is what we see from the CStree.

   # TODO With DAG, without DAG, number of samples changes
                                        

** Vitamin-D dataset
   This dataset comes from a real study on Vitamin D and mortality cite:martinussen-2017-instr-variab, and contains 4 feature variables corresponding to age, a binary indicator denoting mutations in the filaggrin gene, vitamin D levels measured  as serum 25-OH-D (nmol/L), follow up time, alongside the predictor variable which is a binary value indicating knowledge of whether the subject passed away during the follow up. Looking at the data it is clear that the ages are grouped into 4 distinct groups. We group the vitamin D measurement into 4 groups based on the quartiles of the data, and the follow up time is grouped into a binary outcome with the median being the cutoff point. We perform the experimental setup 1 and 2 on this dataset and get the following results.

   #+begin_export latex
% Please add the following required packages to your document preamble:
% \usepackage{multirow}
\begin{table*}[]\label{table:vitd1}
\begin{tabular}{cccccccccccccccc}
\cline{3-12}
                        & \multicolumn{1}{c|}{\multirow{\begin{tabular}[c]{@{}c@{}}Goal:\\ Min stages\end{tabular}}} & \multicolumn{2}{c|}{Anderson}                                           & \multicolumn{2}{c|}{Epps}                                           & \multicolumn{2}{c|}{SKL $5\times 10^{-1}$}                                         & \multicolumn{2}{c|}{SKL $5	\times 10^{-2}$}                                     & \multicolumn{2}{c|}{SKL $5\times 10^{-4}$}                                     &  &  &  &  \\ \cline{3-12}
                        & \multicolumn{1}{c|}{}                                                                            & \multicolumn{1}{c|}{Stages}     & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages}     & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              &  &  &  &  \\ \cline{3-12}
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{12}         & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}         & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{PC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5}          & \multicolumn{1}{c|}{13}     & \multicolumn{1}{c|}{-8800.0}          & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5}          & \multicolumn{1}{c|}{5}      & \multicolumn{1}{c|}{-8771.7}          & \multicolumn{1}{c|}{9}      & \multicolumn{1}{c|}{-8532.3}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{6}          & \multicolumn{1}{c|}{-8480.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1}          & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5}          & \multicolumn{1}{c|}{9}      & \multicolumn{1}{c|}{\textbf{-8405.2}}          & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                         & \multicolumn{1}{c|}{26}         & \multicolumn{1}{c|}{-8462.3}          & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3}          & \multicolumn{1}{c|}{26}         & \multicolumn{1}{c|}{-8462.3}          & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3}          & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{HC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                     & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5}          & \multicolumn{1}{c|}{36}     & \multicolumn{1}{c|}{-8871.7}          & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5}          & \multicolumn{1}{c|}{5}      & \multicolumn{1}{c|}{-8771.7}          & \multicolumn{1}{c|}{9}      & \multicolumn{1}{c|}{-8526.3}          &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                   & \multicolumn{1}{c|}{5}          & \multicolumn{1}{c|}{-8771.7}          & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-8701.7}          & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5}          & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-8413.0} & \multicolumn{1}{c|}{14}     & \multicolumn{1}{c|}{-8418.0}          &  &  &  &  \\ \cline{2-12}
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             & \textbf{}                             &  &  &  &  \\
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  &  \\
                        &                                                                                                  &                                 &                                       &                             &                                       &                                 &                                       &                             &                                       &                             &                                       &  &  &  & 
\caption{Experimental setup 1 on the Vitamin D dataset}
			\end{tabular}
\end{table*}





% Please add the following required packages to your document preamble:
% \usepackage{multirow}
\begin{table*}[]
\begin{tabular}{cccccccccccccccc}
\cline{3-12}
                        & \multicolumn{1}{c|}{\multirow{\begin{tabular}[c]{@{}c@{}}Goal:\\ Max BIC\end{tabular}}} & \multicolumn{2}{c|}{Anderson}                              & \multicolumn{2}{c|}{Epps}                                  & \multicolumn{2}{c|}{SKL $5\times10^{-1}$}                                & \multicolumn{2}{c|}{SKL $5	\times10^{-2}$}                                     & \multicolumn{2}{c|}{SKL $5\times 10^{-4}$}                            &  &  &  &  \\ \cline{3-12}
                        & \multicolumn{1}{c|}{}                                                                         & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages}     & \multicolumn{1}{c|}{BIC}     & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}              & \multicolumn{1}{c|}{Stages} & \multicolumn{1}{c|}{BIC}     &  &  &  &  \\ \cline{3-12}
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                      & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}         & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1}          & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{PC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                  & \multicolumn{1}{c|}{6}      & \multicolumn{1}{c|}{-8487.9} & \multicolumn{1}{c|}{14}     & \multicolumn{1}{c|}{-8500.0} & \multicolumn{1}{c|}{5}          & \multicolumn{1}{c|}{-8749.9} & \multicolumn{1}{c|}{19}     & \multicolumn{1}{c|}{-8428.2}          & \multicolumn{1}{c|}{37}     & \multicolumn{1}{c|}{-8489.0} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                & \multicolumn{1}{c|}{6}      & \multicolumn{1}{c|}{-8480.1} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} & \multicolumn{1}{c|}{5}          & \multicolumn{1}{c|}{-8749.9} & \multicolumn{1}{c|}{9}      & \multicolumn{1}{c|}{\textbf{-8405.2}} & \multicolumn{1}{c|}{12}     & \multicolumn{1}{c|}{-8410.1} &  &  &  &  \\ \cline{2-12}
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{DAG}                                                                      & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3} & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3} & \multicolumn{1}{c|}{26}         & \multicolumn{1}{c|}{-8462.3} & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3}          & \multicolumn{1}{c|}{26}     & \multicolumn{1}{c|}{-8462.3} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{\rotatebox{90}{HC}} & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w DAG\end{tabular}}                  & \multicolumn{1}{c|}{5}      & \multicolumn{1}{c|}{-8779.6} & \multicolumn{1}{c|}{36}     & \multicolumn{1}{c|}{-8871.7} & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5} & \multicolumn{1}{c|}{8}      & \multicolumn{1}{c|}{-8487.9}          & \multicolumn{1}{c|}{13}     & \multicolumn{1}{c|}{-8525.8} &  &  &  &  \\ \cline{2-12}
\multicolumn{1}{c|}{}   & \multicolumn{1}{c|}{\begin{tabular}[c]{@{}c@{}}CSTree \\ w/o DAG\end{tabular}}                & \multicolumn{1}{c|}{5}      & \multicolumn{1}{c|}{-8771.7} & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-8701.7} & \multicolumn{1}{c|}{\textbf{4}} & \multicolumn{1}{c|}{-9041.5} & \multicolumn{1}{c|}{11}     & \multicolumn{1}{c|}{-8413.0}          & \multicolumn{1}{c|}{14}     & \multicolumn{1}{c|}{-8418.0} &  &  &  &  \\ \cline{2-12}
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  &  \\
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  &  \\
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  &  \\
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             & \textbf{}                    &  &  &  &  \\
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  &  \\
                        &                                                                                               &                             &                              &                             &                              &                                 &                              &                             &                                       &                             &                              &  &  &  & 

\caption{Experimental setup 2 on the Vitamin D dataset}
			\end{tabular}
\end{table*}
   #+end_export

   # TODO Analysis of vitamind 1 exp 1

 

   
   # !!! TODO Cite table number above

   # TODO Print all possible orderings

   # TODO Skipped tests due to single values


   
** Discussion of empirical performance

   We see in general that using the symmetric KL divergence to identify stages in the CStree result a higher BIC score when compared to choosing a CStree with the minimum number of stages. There are many reasons which could lead to this happening in practice, with the first being unreliability of the statistical independence tests, which is in general a very task cite:shah-2020-hardn-condit.


   If the data generating distribution happens to be faithful to a CStree with a large number of stages, particularly non-singleton stages, then it is possible that there is not enough samples to learn the context specific information in the finite data setting. We note that a lot of this information was learnt by comparing samples with extremely different sizes, so in practice it might be a good idea to merge the corresponding nodes into the same stage if a certain criteria is met, for example, only if both sample sizes are at least half of their mean.


   The instability of DAG learning algorithms used to get the causal orderings also play a crucial role, and we observed this in practice. For example, we observed that if we happen to know the causal ordering and then feed it to the algorithm, we could learn a DAG in the initial step whose MEC contains no DAGs which are consistent with this causal ordering.  This may also present itself to be a problem if we have partial knowledge of the ordering, for example in the mice cortex data experiment, it is plausible to think of the predictor class to be a function of the gene expression levels.


   One important aspect of this process is to choose the best CStree from all possible causal ordering, which is a model selection problem. In Algorithm \ref{alg:cstreepc} we opt to choose the one with the fewest stages since it relates to choosing the model with the fewest parameters, i.e. the simplest model. This goes in hand with the principle of Occam's razor - in the face of many possible models, choose the simplest model. Here a simple model refers to one which has few parameters. In practice however we see that problems arising due to misleading conditional independence tests and small data samples might lead to the simplest model being too simple, compromising the fit to the data.


   # TODO Something about orderings


* Conclusions
** Summary
   We start with DAGs as a means to encode CI relations, and how one can use the characterization of Markov Equivalence in DAGs to learn causal structure through CI testing. We then cover the limitations of CI relations in comparison to CSI relations, and go over CStrees as a means to encode such CSI relations. We then show how one can learn these CSI relations from observational data and learn a CStree, and how to compute minimal contexts which are important when it comes to visualizing higher dimensional CStrees. We then apply these techniques to synthetic and real data.

   
** Future work
   One of the more natural extensions of this work is to learn CStrees from interventional data. This can already be done with DAGs cite:yang-2018-charac-learn. On the topic of model selection, it might be interesting to see the applicability of Bayesian model selection for CStrees, whereby the model evidence is used as the basis for comparing models which automatically penalizes over-complex models whilst also penalizing models which do not agree with the observed data cite:mackay-1992-bayes-inter. Similar approaches have been applied to Gaussian DAG models cite:castelletti-2020-bayes-model. Generalization to missing data problems would also be an interesting avenue, considering that the PC algorithm has been recently extended for missing data instances in DAGs cite:tu-2019-causal-discov. But perhaps the most impactful extension would be formulating the problem of finding the best CStree into a continuous optimization problem, which can lead to scalable score based methods. Recent work has formulate the problem of searching for the best DAG according to some metric by using a characterization of acyclicity that is smooth and exact, allowing the conversion of the combinatorial problem into a purely continuous problem cite:zheng-2018-dags-no-tears. 
   

   

{{{NEWPAGE}}}



bibliographystyle:unsrt
bibliography:~/Dropbox/org/bibliography/references.bib

{{{NEWPAGE}}}
# * TODO General
#  - DAG To CStree, (1,4)(1,3)(3,5) 2 alone did not work?
#    Also (1,2),(1,4),(1,5),(2,4),(2,5)
#  - Recheck gettign CSI relations from the tree

#  - On recovering the empty context graph but with the wrong trees

#  - Explicitly mention getting the case where for minimal contexts you can have for a given pair contexts involving (1,2,3), (1,2) and (4,5) in which case T must be empty
#    A very important case that the contexts provided 

 # - Explain the special case for the DAG to cstree algorithm, second variable if independent of the first this means 2_||_1 and we colour all nodes in level 1 the same as well
 # - put paths and blocked paths visualization, intuition of information flowing

# faithfulness as a particular form of occams razor

# experimentation - randomized controlledtrials , A/b testings, visualize like mooijs slide separating sample into subsets, applying intervention and plcebo, measureing outcomes etc
# - pipeline visualization
# - rcts as dags, assumptions  - outcome does not cause treatment, outcome and treatment are unconfounded cite mooij paper joint causal inference a unifyin g perspective

# - table with number of dags and cstrees tabel
# - increasing sequence of sets from distributions to markov distributions od dags, to markov distributions of cstrees

# - separate the use of DAGs for probabilistic modelling, and causal modelling - fundamental assumption of different semantics where the observational and interventiona ldistributions are the same for no parents. then no reason to assume parent-child distributions should stay the same under intervention - modularity property.
# - probabilistic dag and causal dag are different! 
# - extended conditional independence when ci relations contain non random variables
# - example of d separation in dags, student studying dag example and use this for maybe the cstree sampling example
# - bayes ball
#  - causal ordering is for trees, linear extension topological ordering is for dags
# - cycles and confounders with mooijs paper in dag limitations
#  - Think about storing stage information in the node itself
#  - http://swoh.web.engr.illinois.edu/courses/IE598/handout/markov.pdf Read intersection lemma and relate to compositional models, relate to pairwise minimal contexts, also read on graphoid case equivalence http://www.stats.ox.ac.uk/~steffen/teaching/cimpa/markov.pdf
#  - For early test stopping make sure CStree property is maintained
#  - Small optimizations e.g. resevouir sampling for randomized node testing
#  - Make efficient use of the Tufte eco system: marginnote, sidenote{<number>}{<offset>}{text}
#  - Desibe the 3 basic DAGs in english for example colliders making two causes compete for each other
#  - Traffic dataset
#  - Generate the data with the aim of making atleast one row all white after DAG to Cstree conversion AND making sure it can learn the DAG from PC first
#  - Gene data in http://proceedings.mlr.press/v119/saeed20a/saeed20a.pdf
#  - PC Python from pgmpy, PC psuedocode from Neapolitan
#  - Quantum paper https://iopscience.iop.org/article/10.1088/1367-2630/17/3/033002/pdf
#  - Marloes Maathuis, High dimensional consistency in score-based and hybrid structure learning: A DAG G is a perfect map of a distribution P if the d-separations in G = conditional independencies in P
#  - Number of DAGs with p nodes and number of CStrees with p binary valued variables
#  - ETH Seminar notes: Constructing minimal I-MAP by taking an ordering, writing the full factorization, drawing corresponding DAG. I-MAPs are important because every distribution is Markov wtih respect to a full DAG, and equivalently, a full DAG is an I-MAP of any distribution. Causal sufficiency i.e. no hidden confounders.
# - add special case for fully connected dag when converting to cstree
 #   - Things added after first draft to Liam: Perfect maps, mention of having to pick cstree based on some criteria
 # - average of number of stages from random dags w varying p
 # average size of pairwise graphoid

  #  - Using algorithmic2e to write functions instead of procedural code https://tex.stackexchange.com/questions/280008/algorithm2e-writing-simple-pseudocode-with-multiple-functions/280038

  # - some cases we might know part of the dag structure for sure in this case maybe its good to add an experiment for this

# Things about model selection
# Intervention data http://www.sciencemag.org/content/suppl/2005/04/21/308.5721.523.DC1/Sachs.SOM.Datasets.zip

* Appendix A
** Remarks on implementation
   Implementation of this work was done in Python. Draft code repository is available at github.com/mnazaal/masters-thesis. This document was generated with org-mode. Use of scikit, pandas, numpy. Test driven development with pytest.
